name: "go-redis"
mode: "dev"
version: "v1.0"
start_time: "2020-07-01"

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

redis:
  host: "127.0.0.1"
  port: "6379"
  password: ""
  db: 0
  pool_size: 100